### ISSUE TITLE
error on mailings screens around mailing_id

### ISSUE THREAD

**Issue by Stoob** [fuzionnz/nz.co.fuzion.idsearch#1]
Upgrade from 5.62 to 5.28.2 produces this error on these mailing screens:
https://site.org/civicrm/mailing/browse/unscheduled?reset=1&scheduled=false

[mailings.error.txt](https://github.com/fuzionnz/nz.co.fuzion.idsearch/files/5111639/mailings.error.txt)

**Comment by eileenmcnaughton** [comment]
@Stoob is this only with this extension enabled?

**Comment by Stoob** [comment]
Yes

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit @petednz

**Comment by jitendrapurohit** [comment]
@Stoob It seems you have another extension loading mailing_id field on the search form?

I wasn't able to replicate the error on a clean install with only this extension enabled. But there's an [update](https://github.com/fuzionnz/nz.co.fuzion.idsearch/commit/fd4b615b37fa1485c1a359c7c954255886243c69) I've made which should avoid loading an element if it already exists on the form (by core updates or any other ext).

Can you pls try the latest master version and confirm if the problem is sorted?

Thanks.

**Comment by Stoob** [comment]
Hi @jitendrapurohit the new version works.  I'm not sure what other extension could have caused it, the problem started after 5.28 update and when I turned this extension off the error went away.  But thanks for fixing!

**Comment by jitendrapurohit** [comment]
cool. Thanks @Stoob
